apiVersion: v1
kind: Service
metadata:
  name: external-lb
spec:
  type: NodePort
  ports:
  - name: nginx
    port: 80
    targetPort: "80-port"
    nodePort: 31600
  # - name: grafana
  #   port: 3000
  #   targetPort: "3000-port"
  #   nodePort: 31610
  selector:
    lbtype: external
---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    lbtype: internal
    app: webapp
  type: ClusterIP
  ports:
  - name: webapp
    protocol: TCP
    port: 8000
    targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  selector:
    lbtype: internal
    app: grafana
  type: ClusterIP
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000