apiVersion: v1
kind: Service
metadata:
  name: external-lb
spec:
  type: LoadBalancer
  ports:
  - name: nginx
    port: 80
    targetPort: "80-port"
  - name: grafana
    port: 3000
    targetPort: "3000-port"
  selector:
    lbtype: external

