apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        lbtype: internal
        app: webapp
    spec:
      containers:
        - name: webapp
          image: iad.ocir.io/id2dt013po6d/infra/webapp:v8.test
          ports:
            - containerPort: 8000
              name: "8000-port"
      imagePullSecrets:
      - name: footy-registry-secret