---
name: Build service and deploy to GCP

on:
  push:
    branches: ['main']

jobs:
  service:
    name: 'Build & Deploy'
    runs-on: 'ubuntu-latest'

    defaults:
      run:
        shell: bash

    env:
      IMAGE_NAME: footy-sync-service
      PROJECT_ID: ${{vars.PROJECT_ID}}
      SERVICE_NAME: ${{vars.SERVICE_NAME}}
      IMAGE_LOCATION: ${{vars.IMAGE_LOCATION}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install Dependencies
      run: pip install -r requirements.txt

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ env.PROJECT_ID }}
        version: '>= 416.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Get Git Tag from commit message'
      id: determine-git-tag
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |-
        bash ./scripts/git_version.sh
        
    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v $GIT_TAG_TYPE
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    
    - name: Docker Image
      run: |-
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME:$GIT_TAG .

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker push $PROJECT_ID/$SERVICE_NAME:$GIT_TAG