---
name: Build service and deploy to GCP

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ["develop", "main"]

jobs:
  service:
    name: 'Build & Deploy'
    runs-on: 'ubuntu-latest'

    defaults:
      run:
        shell: bash

    env:
      IMAGE_NAME: footy-sync-service
      PROJECT_ID: ${{vars.PROJECT_ID}}
      SERVICE_NAME: ${{vars.SERVICE_NAME}}
      IMAGE_LOCATION: ${{vars.IMAGE_LOCATION}}
      REPOSITORY_NAME: ${{vars.REPOSITORY_NAME}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install Dependencies
      run: pip install -r requirements.txt

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ env.PROJECT_ID }}
        version: '>= 416.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Get Git Tag from commit message'
      id: determine-git-tag
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |-
        bash ./scripts/git_version.sh
        
    - name: Automatic Tagging of Releases
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: increment-git-tag
      run: |
        bash ./scripts/git_update.sh -v $GIT_TAG_TYPE
    
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker $IMAGE_LOCATION --quiet
    
    - name: Docker Image
      run: |-
        docker build -t $SERVICE_NAME .

    - name: Tag Image with Default
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: |-
        docker tag $SERVICE_NAME $IMAGE_LOCATION/$PROJECT_ID/$REPOSITORY_NAME/$SERVICE_NAME
    
    - name: Tag Image with Git Version
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |-
        docker tag $SERVICE_NAME $IMAGE_LOCATION/$PROJECT_ID/$REPOSITORY_NAME/$SERVICE_NAME:$GIT_TAG

    - name: Push Docker Image with Default Tag to Artifact Registry
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: |-
        docker push $IMAGE_LOCATION/$PROJECT_ID/$REPOSITORY_NAME/$SERVICE_NAME

    - name: Push Docker Image with Git Tag to Artifact Registry
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |-
        docker push $IMAGE_LOCATION/$PROJECT_ID/$REPOSITORY_NAME/$SERVICE_NAME:$GIT_TAG
    
