webapp:
  name: footy-sync
  lbtype: internal
  selectorLabels: footy-sync

image: 
  repository: iad.ocir.io/id2dt013po6d/newyeti/footy-sync
  tag: v1.2-amd

service: 
  port: 8000
  targetPort: 8000

imagePullSecrets: footy-registry-secret

secret: footy-secrets

google_cloud_project: newyeti

app_env: prod

observability:
  tempo: http://tempo:4317